name: Deploy makelemonad-prr

on:
  push:
    branches: [main]
    paths:
      - 'apps/makelemonad-prr/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_MAKE }}
          accountId: 8978598388ccc2513f2f23b68b9eed8c
          projectName: makelemonad-prr
          directory: apps/makelemonad-prr
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
